// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSwitchWeb.Database;

#nullable disable

namespace SmartSwitchWeb.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220119164616_InitialCreateV5")]
    partial class InitialCreateV5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SmartSwitchWeb.Data.Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceID");

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageID");

                    b.HasIndex("DeviceID");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.RepeatPattern", b =>
                {
                    b.Property<int>("RepeatPatternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DayFlags")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("HourFlags")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MinuteFlags")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("MonthFlags")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("WeekdayFlags")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkloadID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RepeatPatternID");

                    b.HasIndex("WorkloadID");

                    b.ToTable("RepeatPatterns", (string)null);
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.Workload", b =>
                {
                    b.Property<int>("WorkloadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationM")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToleranceDurationM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkloadDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkloadW")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkloadID");

                    b.ToTable("Workload", (string)null);
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.Message", b =>
                {
                    b.HasOne("SmartSwitchWeb.Data.Device", "Device")
                        .WithMany("Messages")
                        .HasForeignKey("DeviceID");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.RepeatPattern", b =>
                {
                    b.HasOne("SmartSwitchWeb.Data.Workload", null)
                        .WithMany("RepeatPattern")
                        .HasForeignKey("WorkloadID");
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.Device", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SmartSwitchWeb.Data.Workload", b =>
                {
                    b.Navigation("RepeatPattern");
                });
#pragma warning restore 612, 618
        }
    }
}
